# App\Entity\Product:
#   properties:
#   name:
#     - NotBlank: { message: "Le nom du produit es tobligatoire" }
#     - Lenght:
#         {
#           min: 3,
#           max: 255,
#           minMessage: "Le nom du produit doit faire plus de 3 caratères",
#         }
#   price:
#     - NotBlank: { message: "Le prix du produit est obligatoire" }
